---

- name: "Debug: Ansible Runner ar_debug={{ ar_debug | bool }}"
  vars:
    msg: |-
      ar_role_version: {{ ar_role_version }}
      ansible_architecture: {{ ansible_architecture }}
      ansible_os_family: {{ ansible_os_family }}
      ansible_distribution: {{ ansible_distribution }}
      ansible_distribution_major_version: {{ ansible_distribution_major_version }}
      ansible_distribution_version: {{ ansible_distribution_version }}
      ansible_distribution_release: {{ ansible_distribution_release }}
      ansible_python_version: {{ ansible_python_version }}

      freebsd_install_method: {{ freebsd_install_method }}
      freebsd_use_packages: {{ freebsd_use_packages }}
      freebsd_install_retries: {{ freebsd_install_retries }}
      freebsd_install_delay: {{ freebsd_install_delay }}
      linux_install_retries: {{ linux_install_retries }}
      linux_install_delay: {{ linux_install_delay }}
      pip_install_retries: {{ pip_install_retries }}
      pip_install_delay: {{ pip_install_delay }}

      ar_supported_linux_family: {{ ar_supported_linux_family }}
      ar_sanity: {{ ar_sanity }}
      ar_sanity_pip_exclusive: {{ ar_sanity_pip_exclusive }}
      ar_sanity_pip_owner_defined: {{ ar_sanity_pip_owner_defined }}
      ar_sanity_pip_exists: {{ ar_sanity_pip_exists }}

      ar_owner: {{ ar_owner }}
      ar_backup_conf: {{ ar_backup_conf }}
      ar_config:
        {{ ar_config | to_yaml(indent=2) | indent(2) }}
      ar_pip_install: {{ ar_pip_install }}
      ar_pip_extraagrs: {{ ar_pip_extraagrs | d('UNDEFINED') }}
      ar_pip_executable: {{ ar_pip_executable }}
      ar_pip_executable_override: {{ ar_pip_executable_override | d('UNDEFINED') }}
      ar_pip_requirements: {{ ar_pip_requirements }}
      ar_pip_requirements_override: {{ ar_pip_requirements_override | d('UNDEFINED') }}
      ar_pip_packages_state: {{ ar_pip_packages_state }}
      ar_pip_packages:
        {{ ar_pip_packages | to_yaml(indent=2) | indent(2) }}
      ar_venv_install: {{ ar_venv_install }}
      ar_virtualenv: {{ ar_virtualenv }}
      ar_virtualenv_command: {{ ar_virtualenv_command | d('UNDEFINED') }}
      ar_virtualenv_python: {{ ar_virtualenv_python | d('UNDEFINED') }}
      ar_virtualenv_site_packages: {{ ar_virtualenv_site_packages | d('UNDEFINED') }}
      ar_virtualenv_packages:
        {{ ar_virtualenv_packages | to_yaml(indent=2) | indent(2) }}
      ar_pkg_install: {{ ar_pkg_install }}
      ar_packages_state: {{ ar_packages_state }}
      ar_packages:
        {{ ar_packages | to_yaml(indent=2) | indent(2) }}
      ar_packages_override: {{ ar_packages_override | d('UNDEFINED') }}
      ar_links:
        {{ ar_links | to_nice_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

# EOF
...
