---

- name: Declare ar_owner when undefined
  when: ar_owner is undefined
  block:

    - name: "Vars: Get the user"
      ansible.builtin.setup:
        gather_subset: user
      become: false

    - name: "Vars: Debug user"
      ansible.builtin.debug:
        msg: |
          ansible_user: {{ ansible_user | d('UDEFINED') }}
          ansible_user_id: {{ ansible_user_id | d('UDEFINED') }}
      when: ar_debug | bool

    - name: "Vars: Declare ar_owner"
      ansible.builtin.set_fact:
        ar_owner: "{{ ansible_user | d(ansible_user_id) }}"

- name: "Vars: Include OS vars"  # noqa: var-naming[no-role-prefix]
  ansible.builtin.include_role:
    name: vbotka.ansible_lib
    tasks_from: al_include_os_vars_path
  vars:
    al_os_vars_path: "{{ ansible_parent_role_paths.0 }}"

- name: "Vars: Override ar_packages"
  ansible.builtin.set_fact:
    ar_packages: "{{ ar_packages_override }}"
  when: ar_packages_override is defined

- name: "Vars: Override ar_pip_executable"
  ansible.builtin.set_fact:
    ar_pip_executable: "{{ ar_pip_executable_override }}"
  when: ar_pip_executable_override is defined

- name: "Vars: Override ar_pip_requirements"
  ansible.builtin.set_fact:
    ar_pip_requirements: "{{ ar_pip_requirements_override }}"
  when: ar_pip_requirements_override is defined

# EOF
...
